language: ruby
cache: bundler
before_script: createdb attr_vault
sudo: false
script: DATABASE_URL="postgres:///attr_vault" bundle exec rspec
addons:
  postgresql: "9.3"
env:
rvm:
  - 2.4.0
notifications:
  email: false
